version: 2.1

defaults: &dockImage
  docker:
    - image: circleci/node:13.8.0


jobs:
  build:
    <<: *dockImage
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    <<: *dockImage
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *dockImage
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
